services:
  # frontend:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #   container_name: frontend
  #   environment:
  #     - PORT=3000
  #     - NODE_ENV=development
  #   restart: always
  #   volumes:
  #     - ./client:/var/www/client
  #     - client-data:/var/www/client/build

  # webserver:
  #   container_name: webserver
  #   restart: unless-stopped
  #   build: ./nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - client-data:/usr/share/nginx/html
  #   depends_on:
  #     - frontend

  cache:
    restart: always
    container_name: cache
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - remise-network

  database:
    image: postgres:16.2-alpine3.19
    restart: always
    container_name: database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=remise
      - POSTGRES_PASSWORD=remise
      - POSTGRES_DB=remisedb
    volumes:
      - ./entrypoint/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro
      - ./entrypoint/postgresql.conf:/etc/postgresql/postgresql.conf
      - db-data:/var/lib/postgresql/data/
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - remise-network

  pgadmin4:
      image: dpage/pgadmin4
      container_name: pgadmin4
      depends_on:
        - database
      ports:
        - "5051:5051"
      environment:
        PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
        PGADMIN_DEFAULT_PASSWORD: root
      restart: always
      networks:
        - remise-network

  backend:
    container_name: backend
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - POSTGRES_USER=remise
      - POSTGRES_PASSWORD=remise
      - POSTGRES_DB=remisedb
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - DEBUG=True
      - SECRET_KEY=django-insecure-&%b)m95ts^a-maxymf__2r0#=ykq#rn%__j#%k7=a8dptj7-m_
    depends_on:
      - database
      - cache
      - pgadmin4
    networks:
      - remise-network
    volumes:
      - ./server:/var/www/server

volumes:
  # client-data:
  redis-data:
  db-data:

networks:
  remise-network:
    name: remise-network
    driver: bridge