# Generated by Django 4.2.5 on 2024-04-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(default='http://example.com', max_length=200),
            preserve_default=False,
        ),
    ]
