# Generated by Django 4.2.5 on 2024-04-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_rate',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
