# Generated by Django 4.2.5 on 2024-05-04 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_remove_product_deleted_remove_product_rank_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.DeleteModel(
            name='Tokens',
        ),
    ]
