# Generated by Django 5.0.4 on 2024-05-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_rename_created_at_product_timestamp_delete_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='admin', max_length=20),
            preserve_default=False,
        ),
    ]
