# Generated by Django 5.0.6 on 2024-05-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_sold',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
